name: replaces

on: 
  workflow_dispatch: # on button click

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      #- name: replace
        #run: find . -type f -exec sed -i 's/\.theme\.css%3FpubDate=230717202833\.css/theme\.css/g' {} +

      - name: replace 2
        run: find . -type f -exec sed -i 's/<script>/<ssscript>/g' {} +

      - name: Save
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Saving...
          file_pattern: '*'
